site_name: Sardine
site_url: https://sardine.raphaelforment.fr
site_author: Raphaël Forment
nav:
  - Home: index.md
  - Showcase: showcase.md
  - Installation / Configuration: 
    - Installing Sardine: 'technical/installation.md'
    - Configuration tools: 'technical/configuration.md'
    - Troubleshooting: 'technical/troubleshot.md'
  - Documentation:
    - Sardinopedia:
      - Introduction: 'documentation/sardinopedia/introduction.md'
      - Survival Kit: 'documentation/survival_kit.md'
      - Learning:
        - Timing and Scheduling: 'documentation/sardinopedia/basic_swimming_lessons.md'
        - Senders & Handlers: 'documentation/sardinopedia/senders.md'
        - The pattern system: 'documentation/sardinopedia/patterning.md'
        - Sardine Pattern Language: 'documentation/sardinopedia/pattern_language.md'
        - SuperCollider & SuperDirt: 'documentation/sardinopedia/supercollider.md'
        - Clock: 'documentation/sardinopedia/clock.md'
      - Demos:
        - Solstice : 'documentation/demos/solstice.md'
        - Zorba in Belleville : 'documentation/demos/zorba_in_belleville.md'
        - Dumpster Dive: 'documentation/demos/dumpster_dive.md'
        - Tribute to Jules Cipher: 'documentation/demos/PMA5.md'
        - Artificial Life: 'documentation/demos/artificial_life.md'
    - Old School Tutorial: 'documentation/tutorial.md'
    - Reference: 'documentation/reference.md'
  - About: about.md
theme:
  palette:
    primary: black
    accent: orange
  font:
    code: Roboto Mono
    text: Karla
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.top
  logo: images/sardine_logo_single.svg
  custom_dir: docs/overrides
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
  - search
docs_dir: docs

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.highlight:
     anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bubobubobubobubo/sardine
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RaphBubo

repo_url: https://github.com/Bubobubobubobubo/sardine

