site_name: Sardine
site_url: https://sardine.raphaelforment.fr
site_author: Raphaël Forment
nav:
  - Home: index.md
  - Showcase: showcase.md
  - Configuration: configuration.md
  - Tutorial: tutorial.md
  - Reference: reference.md
  - About: about.md
theme:
  palette:
    primary: black
    accent: orange
  font:
    code: Roboto Mono
    text: Roboto Mono
  name: material
  icon:
    repo: fontawesome/brands/git-alt

extra:
  generator: false
plugins:
  - search
docs_dir: docs

markdown_extensions:
  - pymdownx.highlight:
     anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bubobubobubobubo/sardine
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RaphBubo

repo_url: https://github.com/Bubobubobubobubo/sardine
