name: Deploy with mkdocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CUSTOM_DOMAIN: sardine.raphaelforment.fr
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
